url: https://y7kim.github.io
baseurl: /gcpug-kr.github.com/

# Site settings
title: GDG Cloud Korea
email: byjungwoon@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Jungwoon Park
  pic: jungwoon
  position: Organizer
  social:
    - title: github
      url: https://github.com/Jungwoon
    - title: linkedin
      url: https://www.linkedin.com/in/jungwoon-park/
    - title: facebook
      url: https://www.facebook.com/byjw.park

- name: Jaeyeon Baek
  pic: jybaek
  position: Organizer
  social:
    - title: facebook
      url: https://www.facebook.com/WeGuardia
    - title: envelope 
      url: mailto:oops.jybaek+gdg@gmail.com

- name: Jonggeon Kim
  pic: 3
  position: Organizer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/googlecloudkorea/
  - title: github
    url: https://github.com/orgs/gcpug-kr/

# Postal address (add as many lines as necessary)
address:
  - line: Seoul Korea

# Build settings
markdown: kramdown
permalink: pretty
